# Fix Travis errors when sending large output to STDOUT. These write errors occurred after
# a Travis update to new Trusty images on Dec. 12th 2017. The reason for these
# write errors is unknown. Using the deprecated builds did not fix the problem.
# Setting 'filter_secrets: false' as suggested here
# https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-321777557
# fixes the problem.
filter_secrets: false

language: python
dist: xenial

python:
  - '3.7'

install:
  - pip3 install HookTest

script: hooktest ./ --scheme epidoc --workers 3 --verbose 10 --manifest --countword --console table --allowfailure --hookUI "https://ci.perseids.org/api/hook/v2.0/user/repositories/PerseusDL/canonical-greekLit"

before_deploy:
  - hooktest-build --travis --txt ./
  - results=$(cat manifest.txt)
  - DATE=`date +%Y-%m-%d`
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$major_version.$minor_version.$TRAVIS_BUILD_NUMBER
  - git add -A
  - git commit -m "Removed failing files" -m "Release $GIT_TAG"
  - git tag $GIT_TAG -a -m "$DATE" -m "PASSING FILES" -m "$results"
  - git push -q https://$GITPERM@github.com/PerseusDL/canonical-greekLit --tags
  - ls -R

deploy:
  provider: releases
  api_key: $GITPERM
 
  on:
    repo: PerseusDL/canonical-greekLit
    branch: master

env:
  global:
    major_version: 0
    minor_version: 0
